# gruvbox material theme
[colors.bright]
black = '#3C3836'
blue = '#7DAEA3'
cyan = '#89B482'
green = '#A9B665'
magenta = '#D3869B'
red = '#EA6962'
white = '#D4BE98'
yellow = '#D8A657'

[colors.dim]
black = '#3C3836'
blue = '#7DAEA3'
cyan = '#89B482'
green = '#A9B665'
magenta = '#D3869B'
red = '#EA6962'
white = '#D4BE98'
yellow = '#D8A657'

[colors.normal]
black = '#3C3836'
blue = '#7DAEA3'
cyan = '#89B482'
green = '#A9B665'
magenta = '#D3869B'
red = '#EA6962'
white = '#D4BE98'
yellow = '#D8A657'

[colors.primary]
background = '#282828'
bright_foreground = '#D4BE98'
dim_foreground = '#D4BE98'
foreground = '#D4BE98'
