-- Reset and register scheme name
vim.cmd('highlight clear')
vim.opt.termguicolors = false
vim.g.colors_name = 'termcolor'

-- " This color scheme relies on ANSI colors only. It automatically inherits
-- " the 16 colors of your terminal color scheme. You can change the colors of
-- " certain highlight groups by picking a different color from the following set
-- " of colors. If you sticked to the ANSI color palette conventions when setting
-- " colors in your terminal emulator, this will look pretty neat. If you used
-- " a terminal color scheme that uses a different convention (e.g. base16)
-- " colors will likely look very odd if you use this color scheme.
-- "
-- " 0: Black        │   8: Bright Black (dark gray)
-- " 1: Red          │   9: Bright Red
-- " 2: Green        │  10: Bright Green
-- " 3: Yellow       │  11: Bright Yellow
-- " 4: Blue         │  12: Bright Blue
-- " 5: Magenta      │  13: Bright Magenta
-- " 6: Cyan         │  14: Bright Cyan
-- " 7: White (gray) │  15: Bright White
-- "
-- " Use the 'cterm' argument to make certain highlight groups appear in italic
-- " (if your terminal and font support it), bold, reverse, underlined, etc.
-- " See ':help attr-list' for possible options.
-- Useful help pages
-- :help termguicolors
-- :help highlight
-- :help highlight-default
-- :help syntax
-- :help treesitter-highlight-groups



vim.api.nvim_set_hl(0, 'NonText', { ctermfg = 0 })
vim.api.nvim_set_hl(0, 'Ignore', { ctermfg = 'NONE', ctermbg = 'NONE' })
vim.api.nvim_set_hl(0, 'Underlined', { underline = true })
vim.api.nvim_set_hl(0, 'Bold', { bold = true })
vim.api.nvim_set_hl(0, 'Italic', { italic = true })
vim.api.nvim_set_hl(0, 'StatusLine', { ctermfg = 15, ctermbg = 8 })
vim.api.nvim_set_hl(0, 'StatusLineNC', { ctermfg = 15, ctermbg = 0 })
vim.api.nvim_set_hl(0, 'VertSplit', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'TabLine', { ctermfg = 1, ctermbg = 0 })
vim.api.nvim_set_hl(0, 'TabLineFill', { ctermfg = 15, ctermbg = 'NONE' })
vim.api.nvim_set_hl(0, 'TabLineSel', { ctermfg = 15, ctermbg = 11 })
vim.api.nvim_set_hl(0, 'Title', { ctermfg = 4, bold = true })
vim.api.nvim_set_hl(0, 'CursorLine', { ctermbg = 0, ctermfg = 'NONE' })
vim.api.nvim_set_hl(0, 'Cursor', { ctermbg = 15, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'CursorColumn', { ctermbg = 0 })
vim.api.nvim_set_hl(0, 'LineNr', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'CursorLineNr', { ctermfg = 6 })
vim.api.nvim_set_hl(0, 'helpLeadBlank', { ctermbg = 'NONE', ctermfg = 'NONE' })
vim.api.nvim_set_hl(0, 'helpNormal', { ctermbg = 'NONE', ctermfg = 'NONE' })
vim.api.nvim_set_hl(0, 'Visual', { ctermbg = 8, ctermfg = 'None', bold = true })
vim.api.nvim_set_hl(0, 'VisualNOS', { ctermbg = 8, ctermfg = 15, bold = true })
vim.api.nvim_set_hl(0, 'Pmenu', { ctermbg = 8, ctermfg = 15})
vim.api.nvim_set_hl(0, 'PmenuSel', { ctermbg = 7, ctermfg = 0, bold = true })
vim.api.nvim_set_hl(0, 'PmenuThumb', { ctermbg = 7, ctermfg = 'NONE' })
vim.api.nvim_set_hl(0, 'FoldColumn', { ctermfg = 7 })
vim.api.nvim_set_hl(0, 'Folded', { ctermfg = 12 })
vim.api.nvim_set_hl(0, 'WildMenu', { ctermbg = 0, ctermfg = 15 })
vim.api.nvim_set_hl(0, 'SpecialKey', { ctermfg = 0 })
vim.api.nvim_set_hl(0, 'IncSearch', { ctermbg = 1, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'CurSearch', { ctermbg = 3, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'Search', { ctermbg = 11, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'Directory', { ctermfg = 4 })
vim.api.nvim_set_hl(0, 'MatchParen', { ctermbg = 0, ctermfg = 3, underline = true })
vim.api.nvim_set_hl(0, 'SpellBad', { undercurl = true })
vim.api.nvim_set_hl(0, 'SpellCap', { undercurl = true })
vim.api.nvim_set_hl(0, 'SpellLocal', { undercurl = true })
vim.api.nvim_set_hl(0, 'SpellRare', { undercurl = true })
vim.api.nvim_set_hl(0, 'ColorColumn', { ctermbg = 8 })
vim.api.nvim_set_hl(0, 'SignColumn', { ctermfg = 7 })
vim.api.nvim_set_hl(0, 'ModeMsg', { ctermbg = 15, ctermfg = 0, bold = true })
vim.api.nvim_set_hl(0, 'MoreMsg', { ctermfg = 4 })
vim.api.nvim_set_hl(0, 'Question', { ctermfg = 4 })
vim.api.nvim_set_hl(0, 'QuickFixLine', { ctermbg = 0, ctermfg = 14 })
vim.api.nvim_set_hl(0, 'Conceal', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'ToolbarLine', { ctermbg = 0, ctermfg = 15 })
vim.api.nvim_set_hl(0, 'ToolbarButton', { ctermbg = 8, ctermfg = 15 })
vim.api.nvim_set_hl(0, 'debugPC', { ctermfg = 7 })
vim.api.nvim_set_hl(0, 'debugBreakpoint', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'ErrorMsg', { ctermfg = 1, bold = true, italic = true })
vim.api.nvim_set_hl(0, 'WarningMsg', { ctermfg = 11 })
vim.api.nvim_set_hl(0, 'DiffAdd', { ctermbg = 10, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'DiffChange', { ctermbg = 12, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'DiffDelete', { ctermbg = 9, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'DiffText', { ctermbg = 14, ctermfg = 0 })
vim.api.nvim_set_hl(0, 'diffAdded', { ctermfg = 10 })
vim.api.nvim_set_hl(0, 'diffRemoved', { ctermfg = 9 })
vim.api.nvim_set_hl(0, 'diffChanged', { ctermfg = 12 })
vim.api.nvim_set_hl(0, 'diffOldFile', { ctermfg = 11 })
vim.api.nvim_set_hl(0, 'diffNewFile', { ctermfg = 13 })
vim.api.nvim_set_hl(0, 'diffFile', { ctermfg = 12 })
vim.api.nvim_set_hl(0, 'diffLine', { ctermfg = 7 })
vim.api.nvim_set_hl(0, 'diffIndexLine', { ctermfg = 14 })
vim.api.nvim_set_hl(0, 'healthError', { ctermfg = 1 })
vim.api.nvim_set_hl(0, 'healthSuccess', { ctermfg = 2 })
vim.api.nvim_set_hl(0, 'healthWarning', { ctermfg = 3 })

-- Syntax
vim.api.nvim_set_hl(0, 'Comment', { ctermfg = 7, italic = true })
vim.api.nvim_set_hl(0, 'Constant', { ctermfg = 3 })
vim.api.nvim_set_hl(0, 'Error', { ctermfg = 1 })
vim.api.nvim_set_hl(0, 'Identifier', { ctermfg = 9 })
vim.api.nvim_set_hl(0, 'Function', { ctermfg = 4 })
vim.api.nvim_set_hl(0, 'Special', { ctermfg = 13 })
vim.api.nvim_set_hl(0, 'Statement', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'String', { ctermfg = 2 })
vim.api.nvim_set_hl(0, 'Operator', { ctermfg = 6 })
vim.api.nvim_set_hl(0, 'Boolean', { ctermfg = 3 })
vim.api.nvim_set_hl(0, 'Label', { ctermfg = 14 })
vim.api.nvim_set_hl(0, 'Keyword', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'Exception', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'Conditional', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'PreProc', { ctermfg = 13 })
vim.api.nvim_set_hl(0, 'Include', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'Macro', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'StorageClass', { ctermfg = 11 })
vim.api.nvim_set_hl(0, 'Structure', { ctermfg = 11 })
vim.api.nvim_set_hl(0, 'Todo', { ctermfg = 0, ctermbg = 9, bold = true })
vim.api.nvim_set_hl(0, 'Type', { ctermfg = 11 })

-- neovim-specific (remove if you're using vim)
vim.api.nvim_set_hl(0, 'NormalFloat', { ctermbg = 0, ctermfg = 15 })
vim.api.nvim_set_hl(0, 'FloatBorder', { ctermbg = 0, ctermfg = 7 })
vim.api.nvim_set_hl(0, 'FloatShadow', { ctermbg = 0, ctermfg = 15 })

-- Treesitter highlighting
-- - allows for more precise syntax highlighting
-- - only available for nvim >0.5
-- - see also :help treesitter-highlight-groups
vim.api.nvim_set_hl(0, '@variable', { ctermfg = 15 })
vim.api.nvim_set_hl(0, '@variable.builtin', { ctermfg = 1 })
vim.api.nvim_set_hl(0, '@variable.parameter', { ctermfg = 1 })
vim.api.nvim_set_hl(0, '@variable.member', { ctermfg = 1 })
vim.api.nvim_set_hl(0, '@constant.builtin', { ctermfg = 5 })
vim.api.nvim_set_hl(0, '@string.regexp', { ctermfg = 1 })
vim.api.nvim_set_hl(0, '@string.escape', { ctermfg = 6 })
vim.api.nvim_set_hl(0, '@string.special.url', { ctermfg = 4, underline = true })
vim.api.nvim_set_hl(0, '@string.special.symbol', { ctermfg = 13 })
vim.api.nvim_set_hl(0, '@type.builtin', { ctermfg = 3 })
vim.api.nvim_set_hl(0, '@property', { ctermfg = 15 })
vim.api.nvim_set_hl(0, '@function.builtin', { ctermfg = 5 })
vim.api.nvim_set_hl(0, '@constructor', { ctermfg = 11 })
vim.api.nvim_set_hl(0, '@keyword.coroutine', { ctermfg = 1 })
vim.api.nvim_set_hl(0, '@keyword.function', { ctermfg = 5 })
vim.api.nvim_set_hl(0, '@keyword.return', { ctermfg = 5 })
vim.api.nvim_set_hl(0, '@keyword.export', { ctermfg = 14 })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { ctermfg = 15 })
vim.api.nvim_set_hl(0, '@comment.error', { ctermbg = 9, ctermfg = 0 })
vim.api.nvim_set_hl(0, '@comment.warning', { ctermbg = 11, ctermfg = 0 })
vim.api.nvim_set_hl(0, '@comment.todo', { ctermbg = 12, ctermfg = 0 })
vim.api.nvim_set_hl(0, '@comment.note', { ctermbg = 14, ctermfg = 0 })
vim.api.nvim_set_hl(0, '@markup', { ctermfg = 15 })
vim.api.nvim_set_hl(0, '@markup.strong', { ctermfg = 15, bold = true })
vim.api.nvim_set_hl(0, '@markup.italic', { ctermfg = 15, italic = true })
vim.api.nvim_set_hl(0, '@markup.strikethrough', { ctermfg = 15, strikethrough = true })
vim.api.nvim_set_hl(0, '@markup.heading', { ctermfg = 4, bold = true })
vim.api.nvim_set_hl(0, '@markup.quote', { ctermfg = 6 })
vim.api.nvim_set_hl(0, '@markup.math', { ctermfg = 4 })
vim.api.nvim_set_hl(0, '@markup.link.url', { ctermfg = 5, underline = true })
vim.api.nvim_set_hl(0, '@markup.raw', { ctermfg = 14 })
vim.api.nvim_set_hl(0, '@markup.list.checked', { ctermfg = 2 })
vim.api.nvim_set_hl(0, '@markup.list.unchecked', { ctermfg = 7 })
vim.api.nvim_set_hl(0, '@tag', { ctermfg = 5 })
vim.api.nvim_set_hl(0, '@tag.builtin', { ctermfg = 6 })
vim.api.nvim_set_hl(0, '@tag.attribute', { ctermfg = 4 })
vim.api.nvim_set_hl(0, '@tag.delimiter', { ctermfg = 15 })

-- Links
vim.api.nvim_set_hl(0, '@variable.parameter.builtin', { link = '@variable.parameter' })
vim.api.nvim_set_hl(0, '@constant', { link = 'Constant' })
vim.api.nvim_set_hl(0, '@constant.macro', { link = 'Macro' })
vim.api.nvim_set_hl(0, '@module', { link = 'Structure' })
vim.api.nvim_set_hl(0, '@module.builtin', { link = 'Special' })
vim.api.nvim_set_hl(0, '@label', { link = 'Label' })
vim.api.nvim_set_hl(0, '@string', { link = 'String' })
vim.api.nvim_set_hl(0, '@string.special', { link = 'Special' })
vim.api.nvim_set_hl(0, '@character', { link = 'Character' })
vim.api.nvim_set_hl(0, '@character.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, '@boolean', { link = 'Boolean' })
vim.api.nvim_set_hl(0, '@number', { link = 'Number' })
vim.api.nvim_set_hl(0, '@number.float', { link = 'Float' })
vim.api.nvim_set_hl(0, '@type', { link = 'Type' })
vim.api.nvim_set_hl(0, '@type.definition', { link = 'Type' })
vim.api.nvim_set_hl(0, '@attribute', { link = 'Constant' })
vim.api.nvim_set_hl(0, '@attribute.builtin', { link = 'Constant' })
vim.api.nvim_set_hl(0, '@function', { link = 'Function' })
vim.api.nvim_set_hl(0, '@function.call', { link = 'Function' })
vim.api.nvim_set_hl(0, '@function.method', { link = 'Function' })
vim.api.nvim_set_hl(0, '@function.method.call', { link = 'Function' })
vim.api.nvim_set_hl(0, '@operator', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@keyword', { link = 'Keyword' })
vim.api.nvim_set_hl(0, '@keyword.operator', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@keyword.import', { link = 'Include' })
vim.api.nvim_set_hl(0, '@keyword.type', { link = 'Keyword' })
vim.api.nvim_set_hl(0, '@keyword.modifier', { link = 'Keyword' })
vim.api.nvim_set_hl(0, '@keyword.repeat', { link = 'Repeat' })
vim.api.nvim_set_hl(0, '@keyword.debug', { link = 'Exception' })
vim.api.nvim_set_hl(0, '@keyword.exception', { link = 'Exception' })
vim.api.nvim_set_hl(0, '@keyword.conditional', { link = 'Conditional' })
vim.api.nvim_set_hl(0, '@keyword.conditional.ternary', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@keyword.directive', { link = 'PreProc' })
vim.api.nvim_set_hl(0, '@keyword.directive.define', { link = 'Define' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { link = 'Delimiter' })
vim.api.nvim_set_hl(0, '@punctuation.special', { link = 'Special' })
vim.api.nvim_set_hl(0, '@comment', { link = 'Comment' })
vim.api.nvim_set_hl(0, '@comment.documentation', { link = 'Comment' })
vim.api.nvim_set_hl(0, '@markup.underline', { link = 'underline' })
vim.api.nvim_set_hl(0, '@markup.link', { link = 'Tag' })
vim.api.nvim_set_hl(0, '@markup.link.label', { link = 'Label' })
vim.api.nvim_set_hl(0, '@markup.list', { link = 'Special' })
vim.api.nvim_set_hl(0, '@diff.plus', { link = 'diffAdded' })
vim.api.nvim_set_hl(0, '@diff.minus', { link = 'diffRemoved' })
vim.api.nvim_set_hl(0, '@diff.delta', { link = 'diffChanged' })
