[general]
live_config_reload = true
import = [
    "~/.cache/theme/alacritty.toml",
]

# [colors.bright]
# black = "#1C1B1A"
# blue = "#4385BE"
# cyan = "#3AA99F"
# green = "#879A39"
# magenta = "#CE5D97"
# red = "#D14D41"
# white = "#6F6E69"
# yellow = "#D0A215"
#
# [colors.dim]
# black = "#3B4252"
# blue = "#81A1C1"
# cyan = "#88C0D0"
# green = "#A3BE8C"
# magenta = "#B48EAD"
# red = "#BF616A"
# white = "#E5E9F0"
# yellow = "#EBCB8B"
#
# [colors.normal]
# black = "#282726"
# blue = "#205EA6"
# cyan = "#24837B"
# green = "#66800B"
# magenta = "#A02F6F"
# red = "#AF3029"
# white = "#878580"
# yellow = "#AD8301"
#
# [colors.primary]
# background = "#FFFCF0"
# bright_foreground = "#D8DEE9"
# dim_foreground = "#D8DEE9"
# foreground = "#100F0F"

[cursor]
style = "Underline"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"
WINIT_HIDPI_FACTOR = "1.0"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 16.0

[font.bold]
family = "UbuntuMono Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font Propo"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
bindings = [
    { action = "PasteSelection", mouse = "Middle" },
]

[scrolling]
history = 10000
multiplier = 3

[window]
# opacity = 0.85
decorations = "none"
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true

[keyboard]
bindings = [
    { chars = "\u001b[13;2u", key = "Return", mods = "Shift" },
    { chars = "\u001b[13;5u", key = "Return", mods = "Control" },
    { action = "ScrollLineDown", key = "J", mods = "Alt" },
    { action = "ScrollLineUp", key = "K", mods = "Alt" },
    { action = "ScrollHalfPageDown", key = "D", mods = "Alt" },
    { action = "ScrollHalfPageUp", key = "U", mods = "Alt" },
    { action = "Paste", key = "V", mods = "Alt" },
    { action = "Paste", key = "V", mods = "Control|Shift" },
    { action = "Paste", key = "Paste" },
    { action = "Copy", key = "C", mods = "Alt" },
    { action = "Copy", key = "C", mods = "Control|Shift" },
    { action = "Copy", key = "Copy" },
    { action = "PasteSelection", key = "P", mods = "Alt" },
    { action = "PasteSelection", key = "Insert", mods = "Shift" },
    { action = "ResetFontSize", key = "Key0", mods = "Control" },
    { action = "IncreaseFontSize", key = "Equals", mods = "Control" },
    { action = "IncreaseFontSize", key = "I", mods = "Alt" },
    { action = "DecreaseFontSize", key = "Minus", mods = "Control" },
    { action = "DecreaseFontSize", key = "O", mods = "Alt" },
    { action = "SearchForward", key = "F", mods = "Control|Shift" },
    { action = "SearchBackward", key = "B", mods = "Control|Shift" },
    { action = "ClearLogNotice", key = "L", mods = "Control" },
    { chars = "\f", key = "L", mode = "~Vi", mods = "Control" },
    { action = "ScrollPageUp", key = "PageUp", mode = "~Alt", mods = "Shift" },
    { action = "ScrollPageDown", key = "PageDown", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToTop", key = "Home", mode = "~Alt", mods = "Shift" },
    { action = "ScrollToBottom", key = "End", mode = "~Alt", mods = "Shift" },
    { action = "ToggleViMode", key = "Space", mods = "Shift|Control" },
    { action = "ScrollToBottom", key = "Space", mode = "Vi", mods = "Shift|Control" },
    { action = "ClearSelection", key = "C", mode = "Vi", mods = "Control|Shift" },
    { action = "ClearSelection", key = "Escape", mode = "Vi" },
    { action = "ScrollToBottom", key = "I", mode = "Vi" },
    { action = "ToggleViMode", key = "I", mode = "Vi" },
    { action = "ScrollLineUp", key = "Y", mode = "Vi", mods = "Control" },
    { action = "ScrollLineDown", key = "E", mode = "Vi", mods = "Control" },
    { action = "ScrollToTop", key = "G", mode = "Vi" },
    { action = "ScrollToBottom", key = "G", mode = "Vi", mods = "Shift" },
    { action = "ScrollPageUp", key = "B", mode = "Vi", mods = "Control" },
    { action = "ScrollPageDown", key = "F", mode = "Vi", mods = "Control" },
    { action = "ScrollHalfPageUp", key = "U", mode = "Vi", mods = "Control" },
    { action = "ScrollHalfPageDown", key = "D", mode = "Vi", mods = "Control" },
    { action = "Copy", key = "Y", mode = "Vi" },
    { action = "ClearSelection", key = "Y", mode = "Vi" },
    { action = "ClearSelection", key = "Copy", mode = "Vi" },
    { action = "ToggleNormalSelection", key = "V", mode = "Vi" },
    { action = "ToggleLineSelection", key = "V", mode = "Vi", mods = "Shift" },
    { action = "ToggleBlockSelection", key = "V", mode = "Vi", mods = "Control" },
    { action = "ToggleSemanticSelection", key = "V", mode = "Vi", mods = "Alt" },
    { action = "Open", key = "Return", mode = "Vi" },
    { action = "Up", key = "K", mode = "Vi" },
    { action = "Down", key = "J", mode = "Vi" },
    { action = "Left", key = "H", mode = "Vi" },
    { action = "Right", key = "L", mode = "Vi" },
    { action = "Up", key = "Up", mode = "Vi" },
    { action = "Down", key = "Down", mode = "Vi" },
    { action = "Left", key = "Left", mode = "Vi" },
    { action = "Right", key = "Right", mode = "Vi" },
    { action = "First", key = "Key0", mode = "Vi" },
    { action = "Last", key = "Key4", mode = "Vi", mods = "Shift" },
    { action = "FirstOccupied", key = "Key6", mode = "Vi", mods = "Shift" },
    { action = "High", key = "H", mode = "Vi", mods = "Shift" },
    { action = "Middle", key = "M", mode = "Vi", mods = "Shift" },
    { action = "Low", key = "L", mode = "Vi", mods = "Shift" },
    { action = "SemanticLeft", key = "B", mode = "Vi" },
    { action = "SemanticRight", key = "W", mode = "Vi" },
    { action = "SemanticRightEnd", key = "E", mode = "Vi" },
    { action = "WordLeft", key = "B", mode = "Vi", mods = "Shift" },
    { action = "WordRight", key = "W", mode = "Vi", mods = "Shift" },
    { action = "WordRightEnd", key = "E", mode = "Vi", mods = "Shift" },
    { action = "Bracket", key = "Key5", mode = "Vi", mods = "Shift" },
    { action = "SearchForward", key = "Slash", mode = "Vi" },
    { action = "SearchBackward", key = "Slash", mode = "Vi", mods = "Shift" },
    { action = "SearchNext", key = "N", mode = "Vi" },
    { action = "SearchPrevious", key = "N", mode = "Vi", mods = "Shift" },
    { chars = "\u001b[13;2u", key = "Return", mods = "Shift" },
    { chars = "\u001b[13;5u", key = "Return", mods = "Control" },
]
